services:
  postgres:
    image: postgres:16-alpine
    container_name: ledger_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ledger_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ledger_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.0
    container_name: ledger_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,secretsmanager
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./src/test/resources/localstack:/etc/localstack/init/ready.d"

volumes:
  postgres_data: